---

- name: Include instance tasks
  include_tasks: instance.yml
  loop: "{{ sphinx_instances }}"
  loop_control:
    loop_var: instance
  when: >
    (sphinx_rollout_instance == '' or instance.name == sphinx_rollout_instance) and
    (instance.state is undefined or instance.state == 'active')
  tags: sphinx
